# Generated by Django 6.0.7 on 2026-08-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repository_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
