# Generated by Django 6.0.7 on 2026-08-17 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='script.py', max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('raw_code', models.TextField()),
                ('quality_score', models.FloatField(default=100.0)),
                ('letter_grade', models.CharField(default='A', max_length=5)),
                ('summary', models.TextField(blank=True, default='')),
                ('suggested_code', models.TextField(blank=True, default='')),
                ('metrics_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyzer', models.CharField(choices=[('AST', 'Python AST'), ('BANDIT', 'Bandit Security'), ('RADON', 'Radon Complexity'), ('RUFF', 'Ruff Linter'), ('GEMINI', 'Gemini AI')], max_length=20)),
                ('category', models.CharField(choices=[('SECURITY', 'Security'), ('COMPLEXITY', 'Complexity'), ('STYLE', 'Code Style'), ('BUG_RISK', 'Bug Risk'), ('DOCUMENTATION', 'Documentation')], max_length=20)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info')], max_length=20)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('code_snippet', models.TextField(blank=True, default='')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('recommendation', models.TextField(blank=True, default='')),
                ('rule_id', models.CharField(blank=True, default='', max_length=50)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='reviews.codereview')),
            ],
            options={
                'ordering': ['line_number', 'severity'],
            },
        ),
    ]
