# Generated by Django 6.0.7 on 2026-08-18 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_language_and_more'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finding',
            name='review',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(default=100)),
                ('security_score', models.IntegerField(default=100)),
                ('quality_score', models.IntegerField(default=100)),
                ('maintainability_score', models.IntegerField(default=100)),
                ('complexity_score', models.IntegerField(default=100)),
                ('performance_score', models.IntegerField(default=100)),
                ('best_practices_score', models.IntegerField(default=100)),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projects.codesubmission')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True, default='')),
                ('suggested_fix', models.TextField(blank=True, default='')),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(max_length=50)),
                ('rule_id', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='reviews.review')),
            ],
            options={
                'ordering': ['line_number', 'severity'],
            },
        ),
        migrations.DeleteModel(
            name='CodeReview',
        ),
        migrations.DeleteModel(
            name='Finding',
        ),
    ]
