# Generated by Django 6.0.7 on 2026-08-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_finding_review_review_reviewissue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='suggested_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
